### ISSUE TITLE
Pale Moon Add-On based on it

### ISSUE THREAD

**Issue by Zero3K** [Linus789/DeepLTranslator#3]
It would be nice if an add-on for Pale Moon that is based on it was made.

**Comment by Linus789** [comment]
You could create the add-on on your own.

**Comment by Zero3K** [comment]
I am not an add-on developer.

**Comment by Zero3K** [comment]
Is it even possible to make one based on it?

**Comment by Linus789** [comment]
Perhaps. I am not a Pale Moon add-on developer.
