### ISSUE TITLE
Why is the translation post-processed?

### ISSUE THREAD

**Issue by BullyWiiPlaza** [Linus789/DeepLTranslator#5]
When translating text, I noticed that line breaks are removed. This messes up my text since I want to keep all line breaks. I debugged the library and found this piece of code:
```
/**
 * Returns the translation, or null if the translation is pending or something went wrong.
 */
private String readResult(JBrowserDriver driver) {
	WebElement webElement = driver.findElementByClassName("lmt__translations_as_text__text_btn");

	if(webElement == null)
		return null;

	String text = webElement.getAttribute("textContent");

	if(text == null)
		return null;

	return text
			.trim()
			.replaceAll("(?:\r?\n)+", " ")
			.replaceAll("\\s{2,}", " ");
}
```
Is there a particular reason for doing the post-processing with `trim()` and `replaceAll()`? Unfortunately it seems like the library does not offer a way to disable this functionality. Removing the post-processing in general or adding an option to disable it would be much appreciated.

**Comment by Linus789** [comment]
Pushed a new version: 1.1.0
```java
DeepLConfiguration deepLConfiguration = new DeepLConfiguration.Builder()
        .setPostProcessing(false)
        .build();

DeepLTranslator deepLTranslator = new DeepLTranslator(deepLConfiguration);
``` 
I only added an option to disable it, so it won't break backwards compatibility. I hope that helps.

**Comment by BullyWiiPlaza** [comment]
Great, perfect job, thanks 👍
