### ISSUE TITLE
Cannot wait for asynchronous translation(s) to finish

### ISSUE THREAD

**Issue by BullyWiiPlaza** [Linus789/DeepLTranslator#7]
Even though the library provides `translateAsync()`, there doesn't seem to be a way to wait for all asynchronous translations to finish: The `ExecutorService` is not accessible: `static final ExecutorService EXECUTOR = Executors.newCachedThreadPool();`
Also, there is no method to wait for all tasks to be finished.

I implemented my own asynchronous wrapper and I found that translations are actually slowed down by multi-threading instead of sped up. I wonder what's up with that? Maybe multi-threaded support isn't properly implemented in the library either? Due to the usage of the `WebDriver` there should be a way of making translations much faster with multiple instances.

**Comment by Chase22** [comment]
This could be solved if #8 is implemented. CompletableFuture has a get method that can wait for execution. It's not directly giving access to the Executor but it would give a possibility of waiting for the task to finish.

**Comment by Linus789** [comment]
Fixed with https://github.com/Linus789/DeepLTranslator/commit/f9bfb02a761ee2599b739de0b7200f28a6cbe9c8.
