### ISSUE TITLE
Using Futures instead of custom callbacks

### ISSUE THREAD

**Issue by Chase22** [Linus789/DeepLTranslator#8]
Java 8 introduced Futures and CompletableFutures. These allow for a Task to either return a value or finish with an exception. Making translateAsync return a completable Future would give the library a standard interface and not require custom implementations.

If wanted i can go ahead and make a pull request for it

**Comment by Linus789** [comment]
Sure, you can create a pull request if you want.

**Comment by Linus789** [comment]
Fixed with https://github.com/Linus789/DeepLTranslator/commit/fb85d5bb5e9b814353f1528aad3f43ca59df6dae.
