### ISSUE TITLE
Use headless Chrome instead of JBrowserDriver

### ISSUE THREAD

**Issue by BullyWiiPlaza** [Linus789/DeepLTranslator#9]
I had major slowness and stability problems with JBrowserDriver used by this library. With headless Chrome things ran perfectly. Maybe migrate this project to headless Chrome using Selenium as dependency. After all, [JBrowserDriver isn't maintained actively anymore](https://github.com/MachinePublishers/jBrowserDriver) and arguably Chrome is far superior anyway:
```
// Supply the chrome driver path
setProperty("webdriver.chrome.driver", chromeDriverFilePath.toString());

// Configure the Chrome instance as headless
ChromeOptions options = new ChromeOptions();
options.addArguments("--headless");

// Start the chrome driver
WebDriver driver = new ChromeDriver(options);
```
Potentially related to this issue: https://github.com/Linus789/DeepLTranslator/issues/6

**Comment by Linus789** [comment]
Fixed with https://github.com/Linus789/DeepLTranslator/commit/cb62f11b4a559a2a84820dde2a247185ff993f7b.
